### ISSUE TITLE
Print List Reports not on Report Manager list

### ISSUE THREAD

**Issue by mkoo** [ArctosDB/arctos#3098]
Why is the report manager list (CFR list to edit handlers) different than the print list? There are labels in the print list which are not on the report manager list so I can edit them? I am checking TEST and they are not in that CFR management list there either. (I see now that they share the reports server so it's kinda a non-issue in test v prod). I cannot update the reports without being able to access them. Uploading a new copy works however.

Print List:
![Firefox_Screenshot_2020-09-09T16-20-39 885Z](https://user-images.githubusercontent.com/2523089/92625830-feecff80-f27d-11ea-82e5-ec176f19c333.png)

Also when I click on ```Manage Reports``` above, I get an error:
```

The following information is meant for the website developer for debugging purposes.
--

Error Occurred While Processing Request
Variable AUTH_KEY is undefined.                                                                                                                                 		         			         			          			The error occurred in /usr/local/httpd/htdocs/internal/reporter/reporter.cfm: line 273          			         					Called from /usr/local/httpd/htdocs/internal/reporter/reporter.cfm: line 268         				         					Called from /usr/local/httpd/htdocs/internal/reporter/reporter.cfm: line 52         				         					Called from /usr/local/httpd/htdocs/internal/reporter/reporter.cfm: line 1         				         			         		     		     			     			          				     						271 :     <form name="n" method="post" enctype="multipart/form-data" action="reporter.cfm"> 272 :         <input type="hidden" name="action" value="loadTemplate"> 273 : 		<input type="hidden" name="auth_key" value="#auth_key#"> 274 :         <input type="file" name="FiletoUpload" id="FiletoUpload" size="45"> 275 :         <input type="submit" class="savBtn" value="Upload File">      					      			         			     			     				     					     				     			     		                                        Resources:              	     	Check the ColdFusion documentation to verify that you are using the correct syntax. 	Search the Knowledge Base to find a solution to your problem.                                                                                  	         	    Browser           		Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0         	         	         		Remote Address           		129.114.52.18         	         	         	    Referrer           		http://reports.arctos.database.museum/reporter/report_printer.cfm?auth_key=0ED38597-46FF-444A-AF1DF463C517B7B9&table_name=temp%5Fcache%2Ess%5Fmkoo%5F20200909110918375%5F606&sort=guid         	         	         	    Date/Time           		09-Sep-20 11:19 AM         	                                                                                                           Stack Trace                                                                               	at  cfreporter2ecfm76796494._factor5(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:273)  	at  cfreporter2ecfm76796494._factor9(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:268)  	at  cfreporter2ecfm76796494._factor10(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:52)  	at  cfreporter2ecfm76796494.runPage(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:1)                                                     coldfusion.runtime.UndefinedVariableException: Variable AUTH_KEY is undefined. 	at coldfusion.runtime.CfJspPage._get(CfJspPage.java:390) 	at coldfusion.runtime.CfJspPage._get(CfJspPage.java:352) 	at coldfusion.runtime.CfJspPage._autoscalarize(CfJspPage.java:1462) 	at cfreporter2ecfm76796494._factor5(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:273) 	at cfreporter2ecfm76796494._factor9(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:268) 	at cfreporter2ecfm76796494._factor10(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:52) 	at cfreporter2ecfm76796494.runPage(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:1) 	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:244) 	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:444) 	at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65) 	at coldfusion.filter.IpFilter.invoke(IpFilter.java:64) 	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:422) 	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:48) 	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40) 	at coldfusion.filter.PathFilter.invoke(PathFilter.java:112) 	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94) 	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28) 	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38) 	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:46) 	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38) 	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22) 	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62) 	at coldfusion.CfmServlet.service(CfmServlet.java:219) 	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) 	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42) 	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224) 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169) 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168) 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98) 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:928) 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:414) 	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:204) 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:539) 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:298) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) 	at java.lang.Thread.run(Thread.java:722) | Variable AUTH_KEY is undefined. |   |   | The error occurred in /usr/local/httpd/htdocs/internal/reporter/reporter.cfm: line 273          			         					Called from /usr/local/httpd/htdocs/internal/reporter/reporter.cfm: line 268         				         					Called from /usr/local/httpd/htdocs/internal/reporter/reporter.cfm: line 52         				         					Called from /usr/local/httpd/htdocs/internal/reporter/reporter.cfm: line 1 | 271 :     <form name="n" method="post" enctype="multipart/form-data" action="reporter.cfm"> 272 :         <input type="hidden" name="action" value="loadTemplate"> 273 : 		<input type="hidden" name="auth_key" value="#auth_key#"> 274 :         <input type="file" name="FiletoUpload" id="FiletoUpload" size="45"> 275 :         <input type="submit" class="savBtn" value="Upload File"> |   | Resources:              	     	Check the ColdFusion documentation to verify that you are using the correct syntax. 	Search the Knowledge Base to find a solution to your problem. | Browser           		Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0         	         	         		Remote Address           		129.114.52.18         	         	         	    Referrer           		http://reports.arctos.database.museum/reporter/report_printer.cfm?auth_key=0ED38597-46FF-444A-AF1DF463C517B7B9&table_name=temp%5Fcache%2Ess%5Fmkoo%5F20200909110918375%5F606&sort=guid         	         	         	    Date/Time           		09-Sep-20 11:19 AM | Browser | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0 | Remote Address | 129.114.52.18 | Referrer | http://reports.arctos.database.museum/reporter/report_printer.cfm?auth_key=0ED38597-46FF-444A-AF1DF463C517B7B9&table_name=temp%5Fcache%2Ess%5Fmkoo%5F20200909110918375%5F606&sort=guid | Date/Time | 09-Sep-20 11:19 AM | Stack Trace | at  cfreporter2ecfm76796494._factor5(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:273)  	at  cfreporter2ecfm76796494._factor9(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:268)  	at  cfreporter2ecfm76796494._factor10(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:52)  	at  cfreporter2ecfm76796494.runPage(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:1)                                                     coldfusion.runtime.UndefinedVariableException: Variable AUTH_KEY is undefined. 	at coldfusion.runtime.CfJspPage._get(CfJspPage.java:390) 	at coldfusion.runtime.CfJspPage._get(CfJspPage.java:352) 	at coldfusion.runtime.CfJspPage._autoscalarize(CfJspPage.java:1462) 	at cfreporter2ecfm76796494._factor5(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:273) 	at cfreporter2ecfm76796494._factor9(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:268) 	at cfreporter2ecfm76796494._factor10(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:52) 	at cfreporter2ecfm76796494.runPage(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:1) 	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:244) 	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:444) 	at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65) 	at coldfusion.filter.IpFilter.invoke(IpFilter.java:64) 	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:422) 	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:48) 	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40) 	at coldfusion.filter.PathFilter.invoke(PathFilter.java:112) 	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94) 	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28) 	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38) 	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:46) 	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38) 	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22) 	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62) 	at coldfusion.CfmServlet.service(CfmServlet.java:219) 	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) 	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42) 	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224) 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169) 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168) 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98) 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:928) 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:414) 	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:204) 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:539) 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:298) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) 	at java.lang.Thread.run(Thread.java:722)
Variable AUTH_KEY is undefined.
 
 
The error occurred in /usr/local/httpd/htdocs/internal/reporter/reporter.cfm: line 273          			         					Called from /usr/local/httpd/htdocs/internal/reporter/reporter.cfm: line 268         				         					Called from /usr/local/httpd/htdocs/internal/reporter/reporter.cfm: line 52         				         					Called from /usr/local/httpd/htdocs/internal/reporter/reporter.cfm: line 1
271 :     <form name="n" method="post" enctype="multipart/form-data" action="reporter.cfm"> 272 :         <input type="hidden" name="action" value="loadTemplate"> 273 : 		<input type="hidden" name="auth_key" value="#auth_key#"> 274 :         <input type="file" name="FiletoUpload" id="FiletoUpload" size="45"> 275 :         <input type="submit" class="savBtn" value="Upload File">
 
Resources:              	     	Check the ColdFusion documentation to verify that you are using the correct syntax. 	Search the Knowledge Base to find a solution to your problem.
Browser           		Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0         	         	         		Remote Address           		129.114.52.18         	         	         	    Referrer           		http://reports.arctos.database.museum/reporter/report_printer.cfm?auth_key=0ED38597-46FF-444A-AF1DF463C517B7B9&table_name=temp%5Fcache%2Ess%5Fmkoo%5F20200909110918375%5F606&sort=guid         	         	         	    Date/Time           		09-Sep-20 11:19 AM | Browser | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0 | Remote Address | 129.114.52.18 | Referrer | http://reports.arctos.database.museum/reporter/report_printer.cfm?auth_key=0ED38597-46FF-444A-AF1DF463C517B7B9&table_name=temp%5Fcache%2Ess%5Fmkoo%5F20200909110918375%5F606&sort=guid | Date/Time | 09-Sep-20 11:19 AM
Browser | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0
Remote Address | 129.114.52.18
Referrer | http://reports.arctos.database.museum/reporter/report_printer.cfm?auth_key=0ED38597-46FF-444A-AF1DF463C517B7B9&table_name=temp%5Fcache%2Ess%5Fmkoo%5F20200909110918375%5F606&sort=guid
Date/Time | 09-Sep-20 11:19 AM
Stack Trace
at  cfreporter2ecfm76796494._factor5(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:273) 
 	at  cfreporter2ecfm76796494._factor9(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:268)  
	at  cfreporter2ecfm76796494._factor10(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:52)
  	at  cfreporter2ecfm76796494.runPage(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:1)                                                     coldfusion.runtime.UndefinedVariableException: Variable AUTH_KEY is undefined.
 	at coldfusion.runtime.CfJspPage._get(CfJspPage.java:390) 
	at coldfusion.runtime.CfJspPage._get(CfJspPage.java:352)
 	at coldfusion.runtime.CfJspPage._autoscalarize(CfJspPage.java:1462) 	
at cfreporter2ecfm76796494._factor5(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:273) 	
at cfreporter2ecfm76796494._factor9(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:268) 	
at cfreporter2ecfm76796494._factor10(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:52) 	
at cfreporter2ecfm76796494.runPage(/usr/local/httpd/htdocs/internal/reporter/reporter.cfm:1) 	
at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:244) 
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:444) 	
at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65) 	
at coldfusion.filter.IpFilter.invoke(IpFilter.java:64) 	
at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:422) 	
at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:48) 
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40) 	
at coldfusion.filter.PathFilter.invoke(PathFilter.java:112) 	
at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
 	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28) 	
at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38) 	
at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:46) 	
at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38) 	
at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22) 	
at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
 	at coldfusion.CfmServlet.service(CfmServlet.java:219) 	
at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89) 	
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) 	
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
 	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42) 	
at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46) 	
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) 	
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) 	
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224) 	
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169) 	
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) 
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168) 	
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98) 	
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:928) 	
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) 
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:414) 	
at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:204) 
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:539) 	
at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:298) 	
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) 	
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) 	
at java.lang.Thread.run(Thread.java:722)

```

**Comment by dustymc** [comment]
>report manager list (CFR list to edit handlers) different than the print list

Somethings missing, probably - I'll need an example to figure it out.

>get an error:

You've got a bunch of tabs open and the (cruddy) authentication has gotten out of sync, most likely.

**Comment by mkoo** [comment]
An example is in the screenshot-- that CFR is not listed in the report manager list.

(of course I have a bunch of tabs open! ok closing a few and purging my search results to only 1. I also will log out of test now that I know I'm in the same reports anyway) --> more purge data buttons?

**Comment by dustymc** [comment]
I think you deleted some things and the janitor scripts haven't caught up yet?

**Comment by mkoo** [comment]
Nope-- I had not delete the MVZ Fish labels and have been looking for them to update!
I did add a new one this morning (prefix with "2") to see if adding something new worked. So I dont know where those are!
If they are deleted then I can just add them back but it is confusing. And now worrisome that my labels disappeared... hence #3097

**Comment by mkoo** [comment]
As threatend in today's meeting, I'm returning to this issue since it really takes priority to fixing the individual reports/labels.

Let me illustrate the issue in case it helps:
At the bottom in Fig 1 is the list of CFR files in the Report Manager that I can edit. Note it has only 3 MVZ_Herp labels with 70etoh in the name. Compare that with what is in the available print menu 
![Screen Shot 2020-09-10 at 2 40 03 PM](https://user-images.githubusercontent.com/2523089/92812408-2d4d0680-f374-11ea-84c7-b71744b4bd85.png)

You can see that there is MVZ_Herps 70etoh, 95etoh, formalin and several MVZ_Fish_100etoh among others that are not available for editing in Fig 1.

Plus the link at the top ```Manage Reports``` sends you to an error not to the Reports Management list.

I did wait to see if some magic script was going to do something but I think the two lists are sorely out of sync from the move. However newly added CFR will show up on the dropdown so not all things are out of whack. Is it possible to a) check to see if there are errant CFR files missing from the manager list since they are showing up in the dropdown? b) check to see if the janitor scripts clean up old unused reports still? Part (a) is critical since none of what to redo a bunch of labels (updating the handler is easy in comparison!) BUT if they are missing then removing from the dropdown so we can start over would be best.

Figure 1: Report Manager:
![Firefox_Screenshot_2020-09-10T21-38-55 901Z](https://user-images.githubusercontent.com/2523089/92812333-1c03fa00-f374-11ea-99e4-3b211645a6d0.png)

**Comment by dustymc** [comment]
>error

Thx fixed

There's a new link at the top of the manage page


<img width="207" alt="Screen Shot 2020-09-10 at 3 14 45 PM" src="https://user-images.githubusercontent.com/5720791/92814764-6dae8380-f378-11ea-8c83-86c9645dc1f3.png">

The first table pull from the data table, and includes a

``#FileExists("#Application.webDirectory#/reporter/templates/#report_template#")#`` column - eg checks to see if the file specified in the report exists

The second works the other way, pulls all CFR files from the directory, loops through them, checks to see what reports they're used with.

I think you've got it, some CFRs are missing. I'd guess that's from the first half of....

<img width="560" alt="Screen Shot 2020-09-10 at 3 30 30 PM" src="https://user-images.githubusercontent.com/5720791/92816632-9b94c780-f37a-11ea-95d3-dddd463395ce.png">

... and it's hard to over-stress the importance of the second half.

**Comment by mkoo** [comment]
Love the new links-- and what about getting the dropdown to reflect exactly whats in the report manager? 

Right now someone is going to pick a report we cant fix/doesnt exist and that will start this whole nonsense again! I can reload our various CFR that are missing right now unless there are enough across all of Arctos to warrant a dive into a backup to retrieve (is that even possible?)

**Comment by dustymc** [comment]
>dropdown to reflect exactly whats in the report manager?

Not really possible - one only works when there's two things, one can deal with only code.

I will add the "missing CFR" check wherever I can though, PG seems happy to support that and it should save some confusion.

>backup

CFRs aren't in the backups (hence the big red warning). I made a couple ZIPs during the PG migration, I think maybe you and @campmlc were involved, I'll keep digging around but I'm not finding them yet....

**Comment by mkoo** [comment]
baby steps: https://github.com/ArctosDB/arctos-assets is a holding repo for downloaded CFR reports. Easy enough for Arctos officers or whoever to do periodically. Serves as backup and place to see all available reports.

@dustymc I'm a little fuzzy now on whether the dropdown will be cleaned up of missing CFR or not? next release or not? this would clear up lots of user confusion

**Comment by dustymc** [comment]
Howto:

<img width="267" alt="Screen Shot 2020-09-16 at 5 33 42 PM" src="https://user-images.githubusercontent.com/5720791/93405793-d4cdab80-f842-11ea-9b61-ab64276a45aa.png">

<img width="145" alt="Screen Shot 2020-09-16 at 5 33 51 PM" src="https://user-images.githubusercontent.com/5720791/93405799-d8f9c900-f842-11ea-8d90-680c395dc24b.png">

https://github.com/ArctosDB/arctos-assets

<img width="320" alt="Screen Shot 2020-09-16 at 5 34 46 PM" src="https://user-images.githubusercontent.com/5720791/93405850-05154a00-f843-11ea-8c9b-1cb3dbb659c8.png">

<img width="354" alt="Screen Shot 2020-09-16 at 5 35 17 PM" src="https://user-images.githubusercontent.com/5720791/93405857-0a729480-f843-11ea-9e72-800e07310ae3.png">

ta-da

<img width="1034" alt="Screen Shot 2020-09-16 at 5 35 54 PM" src="https://user-images.githubusercontent.com/5720791/93405885-1bbba100-f843-11ea-808c-f2573ee64e43.png">

>missing CFR

It's not really a release - it's a distinct box with its own code - just need to prioritize.

/remind me to do that on Thursday

**Comment by dustymc** [comment]
Dropdown should be filtering, and I added the opposite to "Show Report-Report" as "Missing Templates:"
