### ISSUE TITLE
Test is down

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#3807]
We just gave access to Alabama Herbarium, need this to be working.

## Error message:

Lucee 5.3.8.189 Error (expression)
--
Message | key [UUID] doesn't exist in the request scope
Stacktrace | The Error Occurred in  /usr/local/webroot/Application.cfc: line 304    302: </div> 303: <p> 304: This message has been logged as #request.uuid# Please 305: <a target="_blank" 306: class="external"
Java Stacktrace | lucee.runtime.exp.ExpressionException: key [UUID] doesn't exist in the request scope 	at lucee.runtime.type.util.StructSupport.invalidKey(StructSupport.java:67) 	at lucee.runtime.type.scope.RequestImpl.get(RequestImpl.java:163) 	at application_cfc$cf$5.udfCall(/Application.cfc:304) 	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106) 	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344) 	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217) 	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:684) 	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572) 	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1911) 	at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:437) 	at lucee.runtime.listener.ModernAppListener.onError(ModernAppListener.java:425) 	at lucee.runtime.listener.MixedAppListener.onError(MixedAppListener.java:138) 	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2485) 	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2447) 	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2418) 	at lucee.runtime.engine.Request.exe(Request.java:44) 	at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1179) 	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1125) 	at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97) 	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 	at java.base/java.lang.Thread.run(Thread.java:834)
Timestamp | 8/4/21 10:39:53 AM CDT

**Comment by dustymc** [comment]
It's not down, it's just running on some less-than-ideal hardware at the moment. It loaded fine for me, it'll load for you, eventually, probably.

Anyone with access needs to CLEARLY understand that this is a test/dev environment, NOT a demo. Being down or broken should be an expectation, and if that's somehow going to negatively influence their view of Arctos then they should not get the invitation.

**Comment by Jegelewicz** [comment]
Check - no more "playing around" in test. That really limits our ability to sell Arctos though.

**Comment by campmlc** [comment]
Some other very limited sandbox we can use for demos?

**Comment by dustymc** [comment]
You can play, you just need to set expectations first. If there's any indication that they're not understanding then I'd recommend steering them away.

If we need a full-performance demo node then we also need a plan to pay for a full-performance demo node.

**Comment by campmlc** [comment]
How much would one cost, say with very limited data?

**Comment by campmlc** [comment]
Could we use it as a mirror?

**Comment by Jegelewicz** [comment]
> Could we use it as a mirror?

NOT if we are going to let people make changes to it...

**Comment by campmlc** [comment]
Yes, that's difficult. Honestly, we haven't had much luck letting people
loose in test. They really need to work with a mentor through the training.

**Comment by Jegelewicz** [comment]
I agree, but everyone says they WANT to try it and saying NO makes it seem like we either aren't capable or it's just too difficult (which is kinda the truth). No answers here and this is a topic for Steering Committee....
