### ISSUE TITLE
Cannot add collection type to part name

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos#4661]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
Trying to add Fish and Inv to part = DNA

**To Reproduce**
1. Go to code table https://arctos.database.museum/info/ctDocumentation.cfm?table=ctspecimen_part_name
2. Click on 'Edit'
3. Scroll down to 'DNA.'
4. Click on 'update'
5. Add Fish
6. Select "save changes"
7. Get error

**Expected behavior**

**Screenshots**
<html><body>

ERROR_ID | EEDCDC29-ADBB-4D50-990B5A80DF901D7A
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | Unterminated string literal started at position  67 in SQL update ctspecimen_part_name set DESCRIPTION=?' where  part_name='DNA'. Expected  char
ERROR_DETAIL |  
ERROR_SQL | update ctspecimen_part_name set  DESCRIPTION='Deoxyribonucleic acid, a molecule composed of two  polynucleotide chains that coil around each other to form a double helix  carrying genetic instructions for the development, functioning, growth  and reproduction of all known organisms and many viruses. Wikipedia'' where part_name='DNA'

</div>
</body>
</html>ERROR_ID 	EEDCDC29-ADBB-4D50-990B5A80DF901D7A
ERROR_TYPE 	SQL
ERROR_MESSAGE 	Unterminated string literal started at position 67 in SQL update ctspecimen_part_name set DESCRIPTION=?' where part_name='DNA'. Expected char
ERROR_DETAIL 	
ERROR_SQL 	update ctspecimen_part_name set DESCRIPTION='Deoxyribonucleic acid, a molecule composed of two polynucleotide chains that coil around each other to form a double helix carrying genetic instructions for the development, functioning, growth and reproduction of all known organisms and many viruses. [Wikipedia](https://en.wikipedia.org/wiki/DNA)'' where part_name='DNA'

request dump:
request
node_name	
string	localhost
rdurl	
string	/includes/forms/f2_ctspecimen_part_name.cfm?DNA
uui	
string	
uuid	
string	EEDCDC29-ADBB-4D50-990B5A80DF901D7A

exception dump:
Catch
Entries: 15
additional	
Struct (ordered)
SQL	
string	update ctspecimen_part_name set DESCRIPTION='Deoxyribonucleic acid, a molecule composed of two polynucleotide chains that coil around each other to form a double helix carrying genetic instructions for the development, functioning, growth and reproduction of all known organisms and many viruses. <a href="https://en.wikipedia.org/wiki/DNA" class="external">Wikipedia</a>'' where part_name='DNA'
DatabaseName	
string	PostgreSQL
DatabaseVersion	
string	12.2
DriverName	
string	PostgreSQL JDBC Driver
DriverVersion	
string	42.2.20
Datasource	
string	user_login
DataSource	
string	user_login
Detail	
string	
ErrorCode	
string	0
Extended_Info	
string	
ExtendedInfo	
string	
Message	
string	Unterminated string literal started at position 67 in SQL update ctspecimen_part_name set DESCRIPTION=?' where part_name='DNA'. Expected char
NativeErrorCode	
number	0
queryError	
string	update ctspecimen_part_name set DESCRIPTION='Deoxyribonucleic acid, a molecule composed of two polynucleotide chains that coil around each other to form a double helix carrying genetic instructions for the development, functioning, growth and reproduction of all known organisms and many viruses. <a href="https://en.wikipedia.org/wiki/DNA" class="external">Wikipedia</a>'' where part_name='DNA'
Sql	
string	update ctspecimen_part_name set DESCRIPTION='Deoxyribonucleic acid, a molecule composed of two polynucleotide chains that coil around each other to form a double helix carrying genetic instructions for the development, functioning, growth and reproduction of all known organisms and many viruses. <a href="https://en.wikipedia.org/wiki/DNA" class="external">Wikipedia</a>'' where part_name='DNA'
SQLState	
string	42601
StackTrace	
string	lucee.runtime.exp.DatabaseException: Unterminated string literal started at position 67 in SQL update ctspecimen_part_name set DESCRIPTION=?' where part_name='DNA'. Expected char at org.postgresql.core.Parser.checkParsePosition(Parser.java:1328) at org.postgresql.core.Parser.parseSql(Parser.java:1235) at org.postgresql.core.Parser.replaceProcessing(Parser.java:1179) at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:43) at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:19) at org.postgresql.util.LruCache.borrow(LruCache.java:123) at org.postgresql.core.QueryExecutorBase.borrowQuery(QueryExecutorBase.java:293) at org.postgresql.jdbc.PgConnection.borrowQuery(PgConnection.java:170) at org.postgresql.jdbc.PgPreparedStatement.<init>(PgPreparedStatement.java:83) at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1295) at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1735) at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:428) at lucee.runtime.db.DatasourceConnectionImpl.getPreparedStatement(DatasourceConnectionImpl.java:198) at lucee.runtime.type.QueryImpl.execute(QueryImpl.java:291) at lucee.runtime.type.QueryImpl.<init>(QueryImpl.java:235) at lucee.runtime.tag.Query.executeDatasoure(Query.java:1134) at lucee.runtime.tag.Query._doEndTag(Query.java:699) at lucee.runtime.tag.Query.doEndTag(Query.java:565) at includes.forms.f2_ctspecimen_part_name_cfm$cf$75.call(/includes/forms/f2_ctspecimen_part_name.cfm:76) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1003) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:926) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:217) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2460) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2450) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2421) at lucee.runtime.engine.Request.exe(Request.java:45) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1179) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1125) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at runwar.Server$1.handleRequest(Server.java:510) at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280) at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260) at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) at java.base/java.lang.Thread.run(Thread.java:829)
TagContext	
Array
1	
Struct
codePrintHTML	
string	74: &lt;cfquery name=&quot;upf&quot; datasource=&quot;user_login&quot; username=&quot;#session.dbuser#&quot; password=&quot;#decrypt(session.epw,session.sessionKey)#&quot;&gt;<br> 75: update ctspecimen_part_name set DESCRIPTION=&lt;cfqueryparam value=&quot;#DESCRIPTION#&quot; CFSQLType=&quot;cf_sql_varchar&quot;&gt;' where part_name='#part_name#'<br> <b>76: &lt;/cfquery&gt;</b><br> 77: &lt;!--- last, insert new if there's one provided ----&gt;<br> 78: &lt;cfif len(COLLECTION_CDE_NEW) gt 0&gt;<br>
codePrintPlain	
string	74: <cfquery name="upf" datasource="user_login" username="#session.dbuser#" password="#decrypt(session.epw,session.sessionKey)#"> 75: update ctspecimen_part_name set DESCRIPTION=<cfqueryparam value="#DESCRIPTION#" CFSQLType="cf_sql_varchar">' where part_name='#part_name#' 76: </cfquery> 77:  78: <cfif len(COLLECTION_CDE_NEW) gt 0>
column	
number	0
id	
string	??
line	
number	76
Raw_Trace	
string	includes.forms.f2_ctspecimen_part_name_cfm$cf$75.call(/includes/forms/f2_ctspecimen_part_name.cfm:76)
template	
string	/usr/local/webroot/includes/forms/f2_ctspecimen_part_name.cfm
type	
string	cfml
type	
string	database
where	
string

**Data**
If this involves external data, attach the __actual__ data that caused the problem. Do not attach a transformation or subset. You may ZIP most formats to attach, or request a Box email address for very large files.

**Desktop (please complete the following information):**

**Additional context**

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.

**Comment by Jegelewicz** [comment]
From https://github.com/ArctosDB/data-migration/issues/764#issuecomment-1122427506
