### ISSUE TITLE
Create Taxon Name with Cloned Classification fails

### ISSUE THREAD

**Issue by DerekSikes** [ArctosDB/arctos#4759]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**

I need to make a new name: Arachnospila arcta

I found the nearest classification to this name to clone, that of 

https://arctos.database.museum/name/Pompilinae

I clicked [Clone classification as new name]

Filled in the fields and clicked the button, it spun its wheels for a bit and gave this time out error below and this other error:

Validator Error: Internal Server Error: error: [object Object]

Lucee [5.3.8.206] - Error (Expression)
Message	request /editTaxonomy.cfm (/usr/local/webroot/editTaxonomy.cfm) has run into a timeout (timeout: 60 seconds) and has been stopped. The thread started 60004ms ago.
Java Stacktrace	
lucee.runtime.exp.RequestTimeoutException: request /editTaxonomy.cfm (/usr/local/webroot/editTaxonomy.cfm) has run into a timeout (timeout: 60 seconds) and has been stopped. The thread started 60004ms ago.
at java.base/java.lang.Thread.getStackTrace(Thread.java:1602)
at lucee.runtime.CFMLFactoryImpl.createRequestTimeoutException(CFMLFactoryImpl.java:671)
at lucee.runtime.util.PageContextUtil.checkRequestTimeout(PageContextUtil.java:213)
at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:924)
at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:907)
at lucee.runtime.PageContextImpl.handlePageException(PageContextImpl.java:2085)
at lucee.runtime.PageContextImpl.handlePageException(PageContextImpl.java:2001)
at lucee.runtime.listener.ModernAppListener.onError(ModernAppListener.java:432)
at lucee.runtime.listener.MixedAppListener.onError(MixedAppListener.java:138)
at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2488)
at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2450)
at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2421)
etc....

When it failed I tried to repeat the process so did it twice and got the same error the 2nd time...

**Priority**
Please assign a priority-label. Unprioritized issues get sent into a black hole of despair.
High - need to be able to make new names!

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/arctos/issues/4754
