### ISSUE TITLE
Login troubles: taking forever, timing out

### ISSUE THREAD

**Issue by szaborac** [ArctosDB/arctos#4772]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Describe the bug**
No change in login page after login attempt. After 4 minutes, I tried opening a new tab and navigating to Arctos, but was not yet logged in. After 8 minutes, I opened another tab and navigated to Arctos, and THAT page showed me as logged in - but the initial browser tab is still waiting. 

At 15 minutes into attempt, the original page timed out. See below for error script.

**To Reproduce**
1. Go to arctos.database.museum
2. Click on 'Log in'
3. Type in login credentials
5. Wait

**Expected behavior**
Log in should happen on the screen I'm attempting to log in on.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac High Sierra 10.13.6
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 101.0.1

**Additional context**
This does not seem to be an issue on Safari, but I only tried Safari AFTER I confirmed I'd logged on successfully on Firefox.

Error message follows:

Lucee [5.3.8.206] - Error (Expression)
--
Message | request  /login.cfm (/usr/local/webroot/login.cfm) has run into a timeout  (timeout: 60 seconds) and has been stopped. The thread started 939028ms  ago.
Java Stacktrace | lucee.runtime.exp.RequestTimeoutException:  request /login.cfm (/usr/local/webroot/login.cfm) has run into a  timeout (timeout: 60 seconds) and has been stopped. The thread started  939028ms ago.	at java.lang.Thread.getStackTrace(Thread.java:1564)	at lucee.runtime.CFMLFactoryImpl.createRequestTimeoutException(CFMLFactoryImpl.java:671)	at lucee.runtime.util.PageContextUtil.checkRequestTimeout(PageContextUtil.java:213)	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:924)	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:907)	at lucee.runtime.PageContextImpl.handlePageException(PageContextImpl.java:2085)	at lucee.runtime.PageContextImpl.handlePageException(PageContextImpl.java:2001)	at lucee.runtime.listener.ModernAppListener.onError(ModernAppListener.java:432)	at lucee.runtime.listener.MixedAppListener.onError(MixedAppListener.java:138)	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2488)	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2450)	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2421)	at lucee.runtime.engine.Request.exe(Request.java:45)	at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1179)	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1125)	at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97)	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51)	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)	at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47)	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) 	at  io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) 	at  io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) 	at  io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) 	at  io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) 	at  io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)	at runwar.Server$1.handleRequest(Server.java:510)	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280)	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260)	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)	at java.lang.Thread.run(Thread.java:750) | lucee.runtime.exp.RequestTimeoutException:  request /login.cfm (/usr/local/webroot/login.cfm) has run into a  timeout (timeout: 60 seconds) and has been stopped. The thread started  939028ms ago. | at java.lang.Thread.getStackTrace(Thread.java:1564) | at lucee.runtime.CFMLFactoryImpl.createRequestTimeoutException(CFMLFactoryImpl.java:671) | at lucee.runtime.util.PageContextUtil.checkRequestTimeout(PageContextUtil.java:213) | at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:924) | at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:907) | at lucee.runtime.PageContextImpl.handlePageException(PageContextImpl.java:2085) | at lucee.runtime.PageContextImpl.handlePageException(PageContextImpl.java:2001) | at lucee.runtime.listener.ModernAppListener.onError(ModernAppListener.java:432) | at lucee.runtime.listener.MixedAppListener.onError(MixedAppListener.java:138) | at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2488) | at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2450) | at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2421) | at lucee.runtime.engine.Request.exe(Request.java:45) | at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1179) | at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1125) | at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97) | at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) | at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) | at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) | at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) | at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47) | at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) | at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) | at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) | at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) | at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) | at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) | at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) | at  io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) | at  io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) | at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) | at  io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) | at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) | at  io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) | at  io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) | at runwar.Server$1.handleRequest(Server.java:510) | at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) | at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280) | at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) | at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) | at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) | at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) | at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) | at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260) | at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) | at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) | at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) | at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) | at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) | at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) | at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) | at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) | at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) | at java.lang.Thread.run(Thread.java:750)
lucee.runtime.exp.RequestTimeoutException:  request /login.cfm (/usr/local/webroot/login.cfm) has run into a  timeout (timeout: 60 seconds) and has been stopped. The thread started  939028ms ago.
at java.lang.Thread.getStackTrace(Thread.java:1564)
at lucee.runtime.CFMLFactoryImpl.createRequestTimeoutException(CFMLFactoryImpl.java:671)
at lucee.runtime.util.PageContextUtil.checkRequestTimeout(PageContextUtil.java:213)
at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:924)
at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:907)
at lucee.runtime.PageContextImpl.handlePageException(PageContextImpl.java:2085)
at lucee.runtime.PageContextImpl.handlePageException(PageContextImpl.java:2001)
at lucee.runtime.listener.ModernAppListener.onError(ModernAppListener.java:432)
at lucee.runtime.listener.MixedAppListener.onError(MixedAppListener.java:138)
at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2488)
at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2450)
at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2421)
at lucee.runtime.engine.Request.exe(Request.java:45)
at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1179)
at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1125)
at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97)
at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47)
at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
at  io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
at  io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
at  io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
at  io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
at  io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at runwar.Server$1.handleRequest(Server.java:510)
at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280)
at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260)
at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
at java.lang.Thread.run(Thread.java:750)

**Priority**
Please assign a priority-label. 
Pri-1.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'm also having some troubles in Chrome. There is also no change in the login page after the login attempt. I can however at least refresh the page and then Arctos will show I am logged in.

**Comment by szaborac** [comment]
If I refresh after 8 minutes (no sooner), I'll be logged in. I'm having
this problem in both Firefox and Chrome, but not Safari.

**Comment by Jegelewicz** [comment]
This was a problem for me a couple of weeks ago, but now it doesn't happen. I am using Firefox 101.0.1 (64-bit)

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
My chrome version is 102.0.5005.115
I'm not having an issue with login in Firefox (101.0.1)

**Comment by szaborac** [comment]
I am - on Firefox version 101.0.1 (64 bit)

**Comment by dustymc** [comment]
merge-->https://github.com/ArctosDB/internal/issues/187
