### ISSUE TITLE
Help needed in Arctos - can't create permit renewal

### ISSUE THREAD

**Issue by ewommack** [ArctosDB/arctos#8376]
# Tell us what you are trying to do 
When I go to create a renewal for a permit I get the following error message. All I've done is click the permit renewal button from the permit edit page. The old permit has all of the previous field filled out, and I can't fill in any new fields until I get the renewal made. I'm not sure how to proceed, or what I am doing wrong. Any help greatly appreciated!

ERROR_ID | E8160C18-4867-40A9-A5AAA44E88D9DD63
-- | --
ERROR_TYPE | SQL
ERROR_MESSAGE | ERROR: syntax error at or near ")" Position: 256
ERROR_DETAIL |  
ERROR_SQL | INSERT INTO permit ( PERMIT_ID, ISSUED_DATE, EXP_DATE, PERMIT_NUM, PERMIT_REMARKS, use_condition, use_condition_summary ) VALUES ( 10002208, {d '2022-01-11'}, {d '2022-12-31'}, '852', 'Renewal of 10002055. (Renewal of 10001944. (Renewal of 10001847. Renewal of 10001673. Renewal of 10001451. Renewal of 10001435. Renewal of 10001434. Renewal of 10001433. Renewal of 10001287.))', null, null, )

</td></tr><tr><td class="luceeH2" style="border: 1px solid rgb(0, 41, 73); vertical-align: top; padding: 2px; empty-cells: show; color: rgb(0, 41, 73); background-color: rgb(70, 143, 175);">where</td><td class="luceeN2" style="border: 1px solid rgb(0, 41, 73); vertical-align: top; padding: 2px; empty-cells: show; color: rgb(0, 41, 73); background-color: rgb(137, 194, 217);"><table style="border-collapse: collapse; font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 11px; empty-cells: show; color: rgb(0, 0, 0);"><tbody><tr><td class="luceeH1" style="border: 1px solid rgb(153, 0, 0); vertical-align: top; padding: 2px; empty-cells: show; color: rgb(153, 0, 0); background-color: rgb(255, 102, 0); font-family: Verdana, Geneva, Arial, Helvetica, sans-serif; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">string</td>ERROR_ID	E8160C18-4867-40A9-A5AAA44E88D9DD63
ERROR_TYPE	SQL
ERROR_MESSAGE	ERROR: syntax error at or near ")" Position: 256
ERROR_DETAIL	
ERROR_SQL	INSERT INTO permit ( PERMIT_ID, ISSUED_DATE, EXP_DATE, PERMIT_NUM, PERMIT_REMARKS, use_condition, use_condition_summary ) VALUES ( 10002208, {d '2022-01-11'}, {d '2022-12-31'}, '852', 'Renewal of [10002055](https://arctos.database.museum/Permit.cfm?Action=editPermit&permit_id=10002055). (Renewal of [10001944](https://arctos.database.museum/Permit.cfm?Action=editPermit&permit_id=10001944). (Renewal of [10001847](https://arctos.database.museum/Permit.cfm?Action=editPermit&permit_id=10001847). Renewal of [10001673](https://arctos.database.museum/Permit.cfm?Action=editPermit&permit_id=10001673). Renewal of [10001451](https://arctos.database.museum/Permit.cfm?Action=editPermit&permit_id=10001451). Renewal of [10001435](https://arctos.database.museum/Permit.cfm?Action=editPermit&permit_id=10001435). Renewal of [10001434](https://arctos.database.museum/Permit.cfm?Action=editPermit&permit_id=10001434). Renewal of [10001433](https://arctos.database.museum/Permit.cfm?Action=editPermit&permit_id=10001433). Renewal of [10001287](https://arctos.database.museum/Permit.cfm?Action=editPermit&permit_id=10001287).))', null, null, )
request dump:

request
node_name	
string	arctos.tacc.utexas.edu
rdurl	
string	/Permit.cfm
uuid	
string	E8160C18-4867-40A9-A5AAA44E88D9DD63
exception dump:

Catch
Entries: 15
additional	
Struct (ordered)
SQL	
string	INSERT INTO permit ( PERMIT_ID, ISSUED_DATE, EXP_DATE, PERMIT_NUM, PERMIT_REMARKS, use_condition, use_condition_summary ) VALUES ( 10002208, {d '2022-01-11'}, {d '2022-12-31'}, '852', 'Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10002055">10002055</a>. (Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001944">10001944</a>. (Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001847">10001847</a>. Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001673">10001673</a>. Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001451">10001451</a>. Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001435">10001435</a>. Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001434">10001434</a>. Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001433">10001433</a>. Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001287">10001287</a>.))', null, null, )
DatabaseName	
string	PostgreSQL
DatabaseVersion	
string	15.4
DriverName	
string	PostgreSQL JDBC Driver
DriverVersion	
string	42.7.3
Datasource	
string	user_login
DataSource	
string	user_login
Detail	
string	
ErrorCode	
string	0
Extended_Info	
string	
ExtendedInfo	
string	
Message	
string	ERROR: syntax error at or near ")" Position: 256
NativeErrorCode	
number	0
queryError	
string	INSERT INTO permit ( PERMIT_ID, ISSUED_DATE, EXP_DATE, PERMIT_NUM, PERMIT_REMARKS, use_condition, use_condition_summary ) VALUES ( 10002208, {d '2022-01-11'}, {d '2022-12-31'}, '852', 'Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10002055">10002055</a>. (Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001944">10001944</a>. (Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001847">10001847</a>. Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001673">10001673</a>. Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001451">10001451</a>. Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001435">10001435</a>. Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001434">10001434</a>. Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001433">10001433</a>. Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001287">10001287</a>.))', null, null, )
Sql	
string	INSERT INTO permit ( PERMIT_ID, ISSUED_DATE, EXP_DATE, PERMIT_NUM, PERMIT_REMARKS, use_condition, use_condition_summary ) VALUES ( 10002208, {d '2022-01-11'}, {d '2022-12-31'}, '852', 'Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10002055">10002055</a>. (Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001944">10001944</a>. (Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001847">10001847</a>. Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001673">10001673</a>. Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001451">10001451</a>. Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001435">10001435</a>. Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001434">10001434</a>. Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001433">10001433</a>. Renewal of <a href="/Permit.cfm?Action=editPermit&permit_id=10001287">10001287</a>.))', null, null, )
SQLState	
string	42601
StackTrace	
string	lucee.runtime.exp.DatabaseException: ERROR: syntax error at or near ")" Position: 256 at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725) at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412) at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371) at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502) at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419) at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194) at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:180) at lucee.runtime.type.util.QueryUtil.execute(QueryUtil.java:353) at lucee.runtime.type.QueryImpl.execute(QueryImpl.java:306) at lucee.runtime.type.QueryImpl.<init>(QueryImpl.java:243) at lucee.runtime.tag.Query.executeDatasoure(Query.java:1133) at lucee.runtime.tag.Query._doEndTag(Query.java:697) at lucee.runtime.tag.Query.doEndTag(Query.java:562) at permit_cfm$cf.call(/Permit.cfm:719) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1060) at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:952) at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:220) at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44) at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2716) at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2702) at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2673) at lucee.runtime.engine.Request.exe(Request.java:45) at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1259) at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1205) at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97) at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51) at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47) at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at runwar.Server$1.handleRequest(Server.java:510) at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:280) at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:260) at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) at java.base/java.lang.Thread.run(Thread.java:829)
TagContext	
Array
1	
Struct
codePrintHTML	
string	717: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;cfqueryparam&nbsp;CFSQLType=&quot;CF_SQL_varchar&quot;&nbsp;value=&quot;#old_permit.use_condition_summary#&quot;&nbsp;null=&quot;#Not&nbsp;Len(Trim(old_permit.use_condition_summary))#&quot;&gt;,<br> 718: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br> <b>719: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/cfquery&gt;</b><br> 720: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;!---&nbsp;bring&nbsp;over&nbsp;old&nbsp;type(s)&nbsp;---&gt;<br> 721: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;cfloop&nbsp;query=&quot;old_permit_type&quot;&gt;<br>
codePrintPlain	
string	717: <cfqueryparam CFSQLType="CF_SQL_varchar" value="#old_permit.use_condition_summary#" null="#Not Len(Trim(old_permit.use_condition_summary))#">, 718: ) 719: </cfquery> 720:  721: <cfloop query="old_permit_type">
column	
number	0
id	
string	??
line	
number	719
Raw_Trace	
string	permit_cfm$cf.call(/Permit.cfm:719)
template	
string	/usr/local/webroot/Permit.cfm
type	
string	cfml
type	
string	database
where	
string

**Comment by dustymc** [comment]
Duplicate of https://github.com/ArctosDB/dev/issues/136??
